# Set working directory to source file

install.packages("GGally")
install.packages("reshape2")
install.packages("lubridate")
install.packages("cluster")
install.packages("fpc")
install.packages("ggmap")
install.packages("gridExtra")
install.packages("grid")
install.packages("shiny")
install.packages("rgl")
install.packages("maps")
install.packages("mapdata")
install.packages("RColorBrewer")
install.packages("../fiftystater_1.0.1.tar.gz", repos = NULL, type = "source")
install.packages("../weatherData_0.5.0.tar.gz", repos = NULL, type = "source")
install.packages("shinythemes")
install.packages("shinydashboard")
install.packages("tidyverse")
install.packages("fiftystater")
install.packages("mapproj")
install.packages("latex2exp")
install.packages("sp")
install.packages("gtable")
install.packages("reshape2")
install.packages("rgbif")
install.packages("fields")
install.packages("geosphere")
install.packages("tibble")
install.packages("proj4")
install.packages("mice")
install.packages("VIM")
install.packages("missForest")
install.packages("ggforce")
install.packages("ggdendro")


